version: '3.9'
services:
    webserver:
        image: nginx:alpine
        container_name: webserver
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - "/opt/docker-volumes/nginx/config/:/etc/nginx/"
            - "/opt/docker-volumes/nginx/data/:/var/www/"
        restart: unless-stopped
        networks: 
            - "nginx_network"          

networks: 
    nginx_network:
        driver: bridge
        ipam: 
            config: 
                - subnet: 192.168.1.1/24
